/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.community;
import javax.swing.table.DefaultTableModel;
import model.Person;
import model.System;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import model.Doctor;
import model.PersonDir;
import model.VitalSigns;
import ui.MainJFrame;
import javax.swing.JOptionPane;
import model.Hospital;
/**
 *
 * @author mingcheng
 */
public class ComAdminJPanel extends javax.swing.JPanel {
    private System sys;
    private JPanel workArea;
    private PersonDir personDir;
    
    public ComAdminJPanel(JPanel workArea, System sys) {
        this.workArea = workArea;
        this.sys = sys;
        initComponents();
        
        createTable(sys.getPersonDir().getPersontList());
        createTable12(sys.getHospitalDir().getHospitalList());
        
    }
    
    
 private void createTable(ArrayList<Person> person){
   
        
     
        DefaultTableModel model = (DefaultTableModel) DisplayTable.getModel();
        model.setRowCount(0); 
        
          
        
        
        for(Person p: person){
                Object [] row = new  Object[5];
                row [0] = p;
               row [1] = p.getAge();
                row [2] = p.getCommunity();
               row [3] = p.getHouse();
          
        
              
                 model.addRow(row);
        }
    /**
     * Creates new form CommunityJPanel
     */

    

    }
 
 private void createTable12(ArrayList<Hospital> hospital){
   
        
     
        DefaultTableModel model = (DefaultTableModel) DisplayHos.getModel();
        model.setRowCount(0); 
        
          
        
        
        for(Hospital hp: hospital){
                Object [] row = new  Object[1];
                row [0] = hp;
           

                 model.addRow(row);
                 
        }
    } 
// private void createTable(){
//      
//      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayTable = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCom = new javax.swing.JTextField();
        txtAdd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnEdit1 = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        btnSearch1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DisplayHos = new javax.swing.JTable();
        btnAdd1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtHosName1 = new javax.swing.JTextField();

        DisplayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Person Name", "Age", "Community", "Address"
            }
        ));
        jScrollPane1.setViewportView(DisplayTable);
        if (DisplayTable.getColumnModel().getColumnCount() > 0) {
            DisplayTable.getColumnModel().getColumn(1).setResizable(false);
            DisplayTable.getColumnModel().getColumn(2).setResizable(false);
            DisplayTable.getColumnModel().getColumn(3).setResizable(false);
        }

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel2.setText("Name:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        jLabel3.setText("Age:");

        jLabel4.setText("Address");

        txtCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComActionPerformed(evt);
            }
        });

        txtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddActionPerformed(evt);
            }
        });

        jLabel5.setText("Community: ");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit1.setText("Edit");
        btnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit1ActionPerformed(evt);
            }
        });

        btnDelete1.setText("Delete");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });

        btnSearch1.setText("Search");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });

        DisplayHos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Hospital Name"
            }
        ));
        jScrollPane2.setViewportView(DisplayHos);

        btnAdd1.setText("Add");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Name:");

        txtHosName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHosName1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAge)
                            .addComponent(txtName)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(16, 16, 16)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(txtCom))))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSearch)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd)
                        .addGap(27, 27, 27)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)))
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHosName1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch1)
                        .addGap(1, 1, 1)
                        .addComponent(btnEdit1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtHosName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEdit1)
                            .addComponent(btnDelete1)
                            .addComponent(btnAdd1)
                            .addComponent(btnSearch1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete)
                            .addComponent(btnEdit)
                            .addComponent(btnAdd)
                            .addComponent(btnSearch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(118, 118, 118))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
          ArrayList<Person> people = new ArrayList<>();

           for(Person p:sys.getPersonDir().getPersontList()){
               if(!(txtName.getText().equals("")||
                    p.getName().equals(txtName.getText()))){
                    continue;
                   
               }
               if(!(txtAge.getText().equals("")||
                    p.getAge()==(Integer.valueOf(txtAge.getText())))){
                    continue;
                   
               }
               if(!(txtCom.getText().equals("")||
                    p.getCommunity().equals(txtCom.getText()))){
                    continue;
                   
               }
               if(!(txtAdd.getText().equals("")||
                    p.getHouse().equals(txtAdd.getText()))){
                    continue;
                   
               }
               
               people.add(p);
               
     
              
           }
            createTable(people);
            
        txtName.setText("");
        txtAge.setText("");
        txtCom.setText("");
        txtAdd.setText("");
        
           
       
                
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComActionPerformed

    private void txtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddActionPerformed
        // TODO add your handling code here:
       
       
       
       
       
       
        
    }//GEN-LAST:event_txtAddActionPerformed

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        // TODO add your handling code here:
         ArrayList<Hospital> hospital = new ArrayList<>();
         boolean b = false;
        for(Hospital hp: sys.getHospitalDir().getHospitalList()){
            if(hp.getName().equals(txtHosName1.getText())){
                b=true;
                hospital.add(hp);
 
            }
          
        }
        if(!b){
                JOptionPane.showMessageDialog(this,"Do not have a match");
            }
            
          createTable12(hospital);  
        
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
       String name = txtName.getText();
       String Age = txtAge.getText();
       String Community = txtCom.getText();
       String Address = txtAdd.getText();
       
       Person np1 = new Person();
       
       np1.setName(name);
       np1.setAge(Integer.valueOf(Age));
       np1.setCommunity(Community);
       np1.setHouse(Address);
       
       sys.getPersonDir().getPersontList().add(np1);
        createTable(sys.getPersonDir().getPersontList());
        
        txtName.setText("");
        txtAge.setText("");
        txtCom.setText("");
        txtAdd.setText("");
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = DisplayTable.getSelectedRow();
       
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to edit");
            return;
        }
         DefaultTableModel model = (DefaultTableModel)DisplayTable.getModel();
         Person selectedPerson = (Person) model.getValueAt(selectedRowIndex,0);
         
         selectedPerson.setName(txtName.getText());
         selectedPerson.setAge(Integer.valueOf(txtAge.getText()));
         selectedPerson.setCommunity(txtCom.getText());
         selectedPerson.setHouse(txtAdd.getText());
         
         createTable(sys.getPersonDir().getPersontList());
         JOptionPane.showMessageDialog(this, "Your Person Info updated");
         txtName.setText("");
        txtAge.setText("");
        txtCom.setText("");
        txtAdd.setText("");
        
         
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = DisplayTable.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Selected Person Info Deleted.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel)DisplayTable.getModel();
        Person selectedEmployee = (Person) model.getValueAt(selectedRowIndex,0);
        
        sys.getPersonDir().getPersontList().remove(selectedEmployee);
        createTable(sys.getPersonDir().getPersontList());
        JOptionPane.showMessageDialog(this, "Selected Person Info Deleted.");
        txtName.setText("");
        txtAge.setText("");
        txtCom.setText("");
        txtAdd.setText("");
        
        
        
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtHosName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHosName1ActionPerformed
            // TODO add your handling code here:
            
    }//GEN-LAST:event_txtHosName1ActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        // TODO add your handling code here:
        Hospital nh = new Hospital();
        nh.setName(txtHosName1.getText());
        sys.getHospitalDir().getHospitalList().add(nh);
        
        createTable12(sys.getHospitalDir().getHospitalList());
        
        
        txtHosName1.setText("");
        
        
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void btnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit1ActionPerformed
        // TODO add your handling code here:
         int selectedRowIndex = DisplayHos.getSelectedRow();
       
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to edit");
            return;
        }
         DefaultTableModel model = (DefaultTableModel)DisplayHos.getModel();
         Hospital selectedHospital = (Hospital) model.getValueAt(selectedRowIndex,0);
         
         selectedHospital.setName(txtHosName1.getText());
         createTable12(sys.getHospitalDir().getHospitalList());
         JOptionPane.showMessageDialog(this, "Your Hospital Info updated");
         txtHosName1.setText("");
        
    }//GEN-LAST:event_btnEdit1ActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = DisplayHos.getSelectedRow();
       
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel)DisplayHos.getModel();
         Hospital selectedHospital = (Hospital) model.getValueAt(selectedRowIndex,0);
         
         sys.getHospitalDir().getHospitalList().remove(selectedHospital);
        createTable12(sys.getHospitalDir().getHospitalList());
        JOptionPane.showMessageDialog(this, "Selected Hospital Info Deleted.");
        txtHosName1.setText("");
    }//GEN-LAST:event_btnDelete1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DisplayHos;
    private javax.swing.JTable DisplayTable;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtAdd;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCom;
    private javax.swing.JTextField txtHosName1;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
