/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.patient;

import java.awt.Component;
import java.awt.HeadlessException;
import java.text.SimpleDateFormat;
import javax.swing.Icon;
import static javax.swing.JOptionPane.DEFAULT_OPTION;
import static javax.swing.JOptionPane.showOptionDialog;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Patient;
import model.PatientDir;
import model.PersonDir;
import model.System;
import ui.MainJFrame;
import javax.swing.JPanel;
import model.Doctor;
import model.Encounter;
import model.Person;
import model.VitalSigns;
import ui.patient.SearchDocJPanel;
/**
 *
 * @author mingcheng
 */
public class SearchDocJPanel extends javax.swing.JPanel {
    PatientDir patientDir;
    private JPanel workArea;
    Person np;
    System sys;
    /**
     * Creates new form NewJPanel
     */
    public SearchDocJPanel(System sys, Person np) {
        
        initComponents();
        this.patientDir = sys.getPatientdir();
        this.np = np;
        this.sys = sys;
        
        cmbRegion.removeAllItems();
        cmbRegion.addItem("Boston");
        cmbRegion.addItem("Malden");
         cmbDoctor.removeAllItems();
//        cmbHospital.removeAllItems();
//        cmbHospital.addItem("HospitalOne");
//        cmbHospital.addItem("HospitalTwo");
//        cmbHospital.addItem("HospitalThree");
//        cmbHospital.addItem("HospitalFour");
//        cmbDoctor.removeAllItems();
        for(Doctor doc:sys.getDoctorDir().getDoctorList()){
            cmbDoctor.addItem(doc.getName());
        }
     
    
//        
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbRegion = new javax.swing.JComboBox<>();
        cmbHospital = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbDoctor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        JDC = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        btnSchedule = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Find a Doctor Here: ");

        jLabel2.setText("Select your region: ");

        cmbRegion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRegionActionPerformed(evt);
            }
        });

        cmbHospital.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Select Hospital: ");

        cmbDoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Select Doctor: ");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("Schedule Appointment Here: ");

        btnSchedule.setText("Ok");
        btnSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScheduleActionPerformed(evt);
            }
        });

        jLabel6.setText("Select a Date: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmbRegion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(JDC, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnSchedule)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel6))
                    .addComponent(JDC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSchedule, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
//     public static void showMessageDialog(Component parentComponent,
//        Object message, String title, int messageType, Icon icon)
//        throws HeadlessException {
//        showOptionDialog(parentComponent, message, title, DEFAULT_OPTION,
//                         messageType, icon, null, null);
//    }
    private void cmbRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRegionActionPerformed
        // TODO add your handling code here:
      
        cmbHospital.removeAllItems();
        
       if((String)cmbRegion.getSelectedItem() == "Boston"){
          cmbHospital.addItem("HospitalOne");
          cmbHospital.addItem("HospitalTwo");
           
        }
        else{
           cmbHospital.addItem("HospitalThree");
           cmbHospital.addItem("HospitalFour");
        }
    }//GEN-LAST:event_cmbRegionActionPerformed
    
    
    private void cmbHospitalActionPerformed(java.awt.event.ActionEvent evt){
        String hospital = (String) cmbHospital.getSelectedItem();
        
        cmbDoctor.removeAllItems();
        
//        if(hospital == "HospitalOne"){
//          cmbDoctor.addItem("Joe");
//          cmbDoctor.addItem("Jane");
//        }
//        else if((String)cmbHospital.getSelectedItem() == "HospitalTwo"){
//           cmbDoctor.addItem("John");
//           cmbDoctor.addItem("Jannis");
//        } 
//        else if((String)cmbHospital.getSelectedItem() == "HospitalThree"){
//           cmbDoctor.addItem("Ann");
//           cmbDoctor.addItem("Carl");
//        }else{
//            cmbDoctor.addItem("Tom");
//            cmbDoctor.addItem("Jim");
//        }
        
    }
    
    
    private void btnScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScheduleActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(this,"You are all set");
        String community = cmbRegion.getSelectedItem()+"";
        String hosptal = cmbHospital.getSelectedItem()+"";
        String docName= cmbDoctor.getSelectedItem()+"";
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
String startDateString = dateFormat.format(JDC.getDate());
       
       
        
        Patient npt = patientDir.addNewPatient(np);
        Doctor doc = findDoc(sys,docName);
        
        VitalSigns vs = new VitalSigns(doc);
        Encounter ne = new Encounter(vs);
        ne.setPatient(npt);
        ne.setDate(startDateString);
        ne.setDoctor(doc);
       
        
        npt.getEh().getEncounterHistory().add(ne);
        
        
        }
        
        
        
        
        
        
        
        
        
//        public Encounter(String patient, String doctor, String date, VitalSigns vitalsigns){
//        this.date = date;
//        this.doctor = doctor;
//        this.patient = patient;
//        this.vitalSigns = vitalSigns;
//        
     public Doctor findDoc(System sys,String doctorName){
         for(Doctor doc:sys.getDoctorDir().getDoctorList()){
            if(doc.getName().equals(doctorName)){
               return doc;
    
        }   
        
     }

        return null;
        
        
    }//GEN-LAST:event_btnScheduleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDC;
    private javax.swing.JButton btnSchedule;
    private javax.swing.JComboBox<String> cmbDoctor;
    private javax.swing.JComboBox<String> cmbHospital;
    private javax.swing.JComboBox<String> cmbRegion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
